### ISSUE TITLE
IE11 / win7: cursor positioned after placeholder text

### ISSUE THREAD

**Issue by gr2m** [gr2m/bootstrap-expandable-input#5]
![screen shot 2015-02-20 at 10 55 41](https://cloud.githubusercontent.com/assets/39992/6284333/362e105c-b8ef-11e4-9847-4f4bdc20cd37.png)
![screen shot 2015-02-20 at 10 55 33](https://cloud.githubusercontent.com/assets/39992/6284334/362f0368-b8ef-11e4-9b74-77f520f675e4.png)

For comparison, here a screenshot how it should look like: The cursor is in the front of the input 
![screen shot 2015-02-20 at 10 57 35](https://cloud.githubusercontent.com/assets/39992/6284346/5f13b2d8-b8ef-11e4-8f3c-65c9dd596b0c.png)

**Comment by zoepage** [comment]
As this is a known bug in IE10 + 11, here an idea:
Take the placeholder text, save it on focus in data-placeholder and empty the value of the placeholder. 
If the field is empty, reverse it.

**Comment by gr2m** [comment]
good idea, but not an option. The placeholder must remain visible when the text is empty

**Comment by zoepage** [comment]
Solution:
http://jsfiddle.net/KX6BY/8/

**Comment by zoepage** [comment]
:focus -> add solution in IE

**Comment by DumboJet** [comment]
@zoepage You are my hero! :) :+1:
